INSERT INTO states (name, code) VALUE ('Alabama', 'US-AL');
INSERT INTO states (name, code) VALUE ('Alaska', 'US-AK');
INSERT INTO states (name, code) VALUE ('Arizona', 'US-AZ');
INSERT INTO states (name, code) VALUE ('Arkansas', 'US-AR');
INSERT INTO states (name, code) VALUE ('California', 'US-CA');
INSERT INTO states (name, code) VALUE ('Colorado', 'US-CO');
INSERT INTO states (name, code) VALUE ('Connecticut', 'US-CT');
INSERT INTO states (name, code) VALUE ('Delaware', 'US-DE');
INSERT INTO states (name, code) VALUE ('Florida', 'US-FL');
INSERT INTO states (name, code) VALUE ('Georgia', 'US-GA');
INSERT INTO states (name, code) VALUE ('Hawaii', 'US-HI');
INSERT INTO states (name, code) VALUE ('Idaho', 'US-ID');
INSERT INTO states (name, code) VALUE ('Illinois', 'US-IL');
INSERT INTO states (name, code) VALUE ('Indiana', 'US-IN');
INSERT INTO states (name, code) VALUE ('Iowa', 'US-IA');
INSERT INTO states (name, code) VALUE ('Kansas', 'US-KS');
INSERT INTO states (name, code) VALUE ('Kentucky', 'US-KY');
INSERT INTO states (name, code) VALUE ('Louisiana', 'US-LA');
INSERT INTO states (name, code) VALUE ('Maine', 'US-ME');
INSERT INTO states (name, code) VALUE ('Maryland', 'US-MD');
INSERT INTO states (name, code) VALUE ('Massachusetts', 'US-MA');
INSERT INTO states (name, code) VALUE ('Michigan', 'US-MI');
INSERT INTO states (name, code) VALUE ('Minnesota', 'US-MN');
INSERT INTO states (name, code) VALUE ('Mississippi', 'US-MS');
INSERT INTO states (name, code) VALUE ('Missouri', 'US-MO');
INSERT INTO states (name, code) VALUE ('Montana', 'US-MT');
INSERT INTO states (name, code) VALUE ('Nebraska', 'US-NE');
INSERT INTO states (name, code) VALUE ('Nevada', 'US-NV');
INSERT INTO states (name, code) VALUE ('New Hampshire', 'US-NH');
INSERT INTO states (name, code) VALUE ('New Jersey', 'US-NJ');
INSERT INTO states (name, code) VALUE ('New Mexico', 'US-NM');
INSERT INTO states (name, code) VALUE ('New York', 'US-NY');
INSERT INTO states (name, code) VALUE ('North Carolina', 'US-NC');
INSERT INTO states (name, code) VALUE ('North Dakota', 'US-ND');
INSERT INTO states (name, code) VALUE ('Ohio', 'US-OH');
INSERT INTO states (name, code) VALUE ('Oklahoma', 'US-OK');
INSERT INTO states (name, code) VALUE ('Oregon', 'US-OR');
INSERT INTO states (name, code) VALUE ('Pennsylvania', 'US-PA');
INSERT INTO states (name, code) VALUE ('Rhode Island', 'US-RI');
INSERT INTO states (name, code) VALUE ('South Carolina', 'US-SC');
INSERT INTO states (name, code) VALUE ('South Dakota', 'US-SD');
INSERT INTO states (name, code) VALUE ('Tennessee', 'US-TN');
INSERT INTO states (name, code) VALUE ('Texas', 'US-TX');
INSERT INTO states (name, code) VALUE ('Utah', 'US-UT');
INSERT INTO states (name, code) VALUE ('Vermont', 'US-VT');
INSERT INTO states (name, code) VALUE ('Virginia', 'US-VA');
INSERT INTO states (name, code) VALUE ('Washington', 'US-WA');
INSERT INTO states (name, code) VALUE ('West Virginia', 'US-WV');
INSERT INTO states (name, code) VALUE ('Wisconsin', 'US-WI');
INSERT INTO states (name, code) VALUE ('Wyoming', 'US-WY');
INSERT INTO states (name, code) VALUE ('District of Columbia', 'US-DC');